Repository request-yo-racks/docs, pull requests merged in 2018-03, with the labels that each got.

#34 Update the documentation
  ryr-docs/docs/guides/setup-full-environment.md
Labels: size/XS, status/pending_review

#35 Simplify the Web documentation
  ryr-docs/docs/guides/setup-full-environment.md
Labels: size/XS

#36 Update ryr config section
  ryr-docs/docs/guides/setup-full-environment.md
Labels: size/XS, status/pending_review

#37 Replace planning canvas
  files/RYR Planning Canvas.png
Labels: kind/docs, size/XS, status/pending_review
